# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Enter your Disqus shortname (not your username) to enable commenting on posts# You can find your shortname on the Settings page of your Disqus accountdisqus: bruttin# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate trackinggoogle_analytics:

# Setup
title:               sacha.bruttin
tagline:             'in my room'
description:         'Hi, my name is Sacha Bruttin and I help people and companies to move to the cloud. I am currently Lead Consultant Microsoft Productivity at <a href="https://www.blue-infinity.com" target="_blank">blue-infinity</a>'
url:                 https://www.bruttin.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sacha Bruttin
  url:               https://twitter.com/sachabruttin
  email:             sacha@bruttin.com
  linkedin:          sachabruttin
  twitter:           sachabruttin
  github:            sachabruttin

# Custom vars
version:             1.0.0

# Gems
gems: [jekyll-paginate]
