# Site settings

baseurl: "" # the subpath of your site, e.g. /blog/
enforce_ssl: bruttin.com # https://sheharyar.me/blog/free-ssl-for-github-pages-with-custom-domains/

email: sacha@bruttin.com # Your contant email

# SEO
title: in my room # Title of your site
description: > # this means to ignore newlines until "baseurl:"
  I am Sacha Bruttin, a
  Cloud Software Architect specialized
  on Azure &amp; .NET development.

url: "https://www.bruttin.com" # the base hostname & protocol for your site
author:
  name: Sacha Bruttin
  twitter: sachabruttin
  picture: /public/me.jpg
twitter:
  username: sachabruttin
social:
  name: Sacha Bruttin
  links:
    - https://twitter.com/sachabruttin
    - https://www.linkedin.com/in/sachabruttin
    - https://github.com/sachabruttin

# Social links.
# Replace the word 'example' with your username if you want to include the icon in the left sidebar
# Delete the word 'example' if you don't want to include the icon in the left sidebar
twitter_username:     sachabruttin  # Replace this with your Twitter username
github_username:      sachabruttin  # Replace this with your GitHub username
linkedin_username:    sachabruttin  # Replace this with your LinkedIn username
google_plus_username:   # Replace this with your Google+ username
facebook_username:      # Replace this with your Facebook username
dribbble_username:      # Replace this with your Dribbble username
feedburner: bruttin

# Build settings
markdown: kramdown

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: bruttin

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-45847559-1

# Pagination
paginate: 3
paginate_path: "/blog/page:num/"

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jemoji
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-redirect-from

# Mentions
jekyll-mentions: https://twitter.com

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# SAAS Settings
sass:
  sass_dir: _sass
  style: compressed

